### ISSUE TITLE
ttn on raspbian

### ISSUE THREAD

**Issue by piechade** [TheThingsNetwork/node-app-sdk#86]
If I try to install ttn on raspbian stretch with the following command:
npm install ttn 

node version
node: v8.11.1
npm: 5.6.0

I get the following error:

```bash
  CXX(target) Release/obj.target/grpc_node/ext/call.o
In file included from ../ext/call.cc:26:0:
../ext/call.h:106:8: error: 'AsyncResource' in namespace 'Nan' does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
In file included from ../ext/call.cc:27:0:
../ext/call_credentials.h:82:8: error: 'AsyncResource' in namespace 'Nan' does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
../ext/call_credentials.h: In constructor 'grpc::node::plugin_callback_data::plugin_callback_data(const char*, grpc_credentials_plugin_metadata_cb, void*)':
../ext/call_credentials.h:71:9: error: class 'grpc::node::plugin_callback_data' does not have any field named 'async_resource'
         async_resource(NULL) {
         ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:5: error: 'async_resource' was not declared in this scope
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
     ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:26: error: expected type-specifier
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
                          ^~~
../ext/call_credentials.h: In destructor 'grpc::node::plugin_callback_data::~plugin_callback_data()':
../ext/call_credentials.h:76:12: error: 'async_resource' was not declared in this scope
     delete async_resource;
            ^~~~~~~~~~~~~~
../ext/call.cc: In constructor 'grpc::node::tag::tag(Nan::Callback*, grpc::node::OpVec*, grpc::node::Call*, v8::Local<v8::Value>)':
../ext/call.cc:450:7: error: class 'grpc::node::tag' does not have any field named 'async_resource'
       async_resource(NULL),
       ^~~~~~~~~~~~~~
../ext/call.cc:454:3: error: 'async_resource' was not declared in this scope
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
   ^~~~~~~~~~~~~~
../ext/call.cc:454:24: error: expected type-specifier
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
                        ^~~
../ext/call.cc: In destructor 'grpc::node::tag::~tag()':
../ext/call.cc:460:10: error: 'async_resource' was not declared in this scope
   delete async_resource;
          ^~~~~~~~~~~~~~
../ext/call.cc: In function 'void grpc::node::CompleteTag(void*, const char*)':
../ext/call.cc:476:41: error: 'struct grpc::node::tag' has no member named 'async_resource'
     callback->Call(2, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~
../ext/call.cc:479:41: error: 'struct grpc::node::tag' has no member named 'async_resource'
     callback->Call(1, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~
grpc_node.target.mk:161: recipe for target 'Release/obj.target/grpc_node/ext/call.o' failed
make: *** [Release/obj.target/grpc_node/ext/call.o] Error 1
make: Leaving directory '/home/owl/apps/test/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/owl/apps/test/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/owl/apps/test/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /home/owl/apps/test/node_modules/grpc
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/owl/apps/test/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/owl/apps/test/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/owl/apps/test/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.34-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/owl/apps/test/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/owl/apps/test/node_modules/grpc
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/owl/apps/test/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/owl/apps/test/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc --napi_version=1 --node_abi_napi=napi' (1)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.11.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.11.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/owl/.npm/_logs/2018-05-14T20_57_13_938Z-debug.log
```

**Comment by Sypheos** [comment]
Seems to be related to grpc compilation. Did you tried updated the compiler ? This could also be related to the architecture of the device you installed raspian on.

**Comment by piechade** [comment]
This seems to fixed it.
````bash
npm explore npm -g -- npm install node-gyp@latest
````

Was not working. What you mean with update compiler?
